### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by AustEcon** [electrumsv/simple-indexer#1]
- [ ] bitcoinx.Headers to tracking sync state - two sets one for node tip and one for indexer tip
- [ ] chain synchronization loop that starts at genesis and goes til == node tip then waits on zmq notifications for the new tip
- [ ] invalidate mempool tx cache entries `on_block`
- [ ] block_headers table for convience of service queries
- [ ] api_state table
